### ISSUE TITLE
Question: How to understand the counterexample generated by nagini?

### ISSUE THREAD

**Issue by RabbitDong-on** [marcoeilers/nagini#212]
Here is code test.py
```python
from nagini_contracts.contracts import *

def power3_A(input:int) -> int:
    out_a=input
    for i in range(2):
        out_a=out_a*input
    return out_a
    
def power3_B(input:int) -> int:
    out_b=(input*input)*input
    return out_b

def main(input:int)->bool:
    Requires(input>0)
    Ensures(Result()==True)
    return power3_A(input)==power3_B(input)
```
I use the command : nagini --counterexample test.py
Output:
```
Verification failed
Errors:
Postcondition of main might not hold. Assertion (Result() == True) might not hold. (NaginiExample.py@15.12--15.26).
Old store:
  input -> 4097
Old heap: Empty.
Current store:
  input -> 4097,
  Result() -> False
Current heap: Empty.
```
4097 does not cause power_A and power_B to output different result. Why does nagini given this counterexample? How to understand the information generated by nagini? Please help me figure out this issue. Thanks a lot.

**Comment by marcoeilers** [comment]
Right, the counterexample says that Nagini cannot prove the postcondition of ``main`` for example in the case of ``i`` being 4097. 
The issue here is that the two ``power_3`` functions do not have any specification, in particular, no postcondition that says anything about the value they return. Nagini does function-modular verification, which means that when calling a function, it only takes into account the specification of that function, not its implementation. Since there is no specification, inside ``main``, Nagini essentially knows nothing about the values returned by the ``power_3``, and thus cannot prove the postcondition.

**Comment by RabbitDong-on** [comment]
Thanks a lot. I will close this issue.

**Comment by marcoeilers** [comment]
So this version for example would verify (if you pull the most recent changes from the master branch, since it turns out there was no support for the ** operator before):

```
from nagini_contracts.contracts import *


def power3_A(input: int) -> int:
    Ensures(Result() == input * input * input)
    out_a = input
    for i in range(2):
        Invariant(out_a == input * (input ** len(Previous(i))))
        out_a = out_a * input
    return out_a


def power3_B(input: int) -> int:
    Ensures(Result() == input * input * input)
    out_b = (input * input) * input
    return out_b


def main(input: int) -> bool:
    Requires(input > 0)
    Ensures(Result() == True)
    return power3_A(input) == power3_B(input)
```

**Comment by RabbitDong-on** [comment]
OK, I just install nagini by pip. I will try new version in master branch.

**Comment by marcoeilers** [comment]
Now (pull changes from master) you can also annotate functions with ``@Inline``, e.g.

```
@Inline
def power3_B(input: int) -> int:
    Ensures(Result() == input * input * input)
    out_b = (input * input) * input
    return out_b
```

so you can avoid writing pre- and postconditions for them and their definitions will be inlined for every call.
